# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 01:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entries', '0002_auto_20170204_1348'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sentiment', models.TextField(default='')),
                ('texttags', models.TextField(default='')),
                ('keywords', models.TextField(default='')),
                ('people', models.TextField(default='')),
                ('places', models.TextField(default='')),
                ('personality', models.TextField(default='')),
                ('emotion', models.TextField(default='')),
                ('personas', models.TextField(default='')),
                ('sentiment_tags', models.TextField(default='')),
                ('sentiment_keywords', models.TextField(default='')),
                ('sentiment_people', models.TextField(default='')),
                ('sentiment_places', models.TextField(default='')),
                ('emotion_tags', models.TextField(default='')),
                ('emotion_keywords', models.TextField(default='')),
                ('emotion_people', models.TextField(default='')),
                ('emotion_places', models.TextField(default='')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_entry', to='entries.Entry')),
            ],
        ),
    ]
