# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 14:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentiment', models.TextField()),
                ('texttags', models.TextField()),
                ('keywords', models.TextField()),
                ('people', models.TextField()),
                ('places', models.TextField()),
                ('personality', models.TextField()),
                ('emotion', models.TextField()),
                ('personas', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField(verbose_name='date added')),
                ('Text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FName', models.CharField(max_length=20)),
                ('LName', models.CharField(max_length=30)),
                ('DOB', models.DateTimeField(verbose_name='date of birth')),
                ('Gender', models.CharField(max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='entry',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='udiaryapp.User'),
        ),
        migrations.AddField(
            model_name='analysis',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='udiaryapp.Entry'),
        ),
    ]
