# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 16:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('udiaryapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='User',
            new_name='Account',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='Date',
        ),
        migrations.AddField(
            model_name='entry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
