# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 20:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('udiaryapp', '0003_auto_20170204_1309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='DOB',
        ),
    ]
