# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='emotion_keywords',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='analysis',
            name='emotion_people',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='analysis',
            name='emotion_places',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='analysis',
            name='emotion_tags',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='analysis',
            name='sentiment_keywords',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='analysis',
            name='sentiment_people',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='analysis',
            name='sentiment_places',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='analysis',
            name='sentiment_tags',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='analysis',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='emotion',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='keywords',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='people',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='personality',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='personas',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='places',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='sentiment',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='texttags',
            field=models.TextField(default=''),
        ),
    ]
